GATE_website/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import index, quizz, documentation, cgu

app_name = 'GATE2'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('quizz/', quizz, name='quizz'),
    path('documentation/', documentation, name='documentation'),
    path('', include('accounts.urls')),
    path('',include('questionnaire.urls')),
    path('cgu/', cgu, name='cgu'),
]

accounts/urls.py
from django.contrib.auth import views
from django.urls import path

from GATE_website.views import index
from .forms import UserLoginForm
from .views import register, supprimer_compte, moncompte

app_name = 'accounts'


urlpatterns = [
    path('login/', views.LoginView.as_view(template_name="accounts/login.html", redirect_authenticated_user=True, authentication_form=UserLoginForm), name='login'),
    path('logout/', views.LogoutView.as_view(template_name="accounts/logout.html", next_page=index), name='logout'),
    path('register/', register, name='register'),
    path('moncompte/', moncompte, name='moncompte'),
    path('supprimer/', supprimer_compte, name='supprimer_compte'),

]

contact/urls.py
from django.contrib.auth import views
from django.urls import path
from .views import contact, redirection



app_name = 'contact'


urlpatterns = [
    path('nous-contacter/', contact, name='contact'),
    path('redirection/', redirection, name="redirection"),
]

questionnaire/urls.py
from django.urls import path

from .views import quizzrep, pddquizz1, pddquizz2, pddquizz3, mdp1,mdp2, pcm1, pcm2, pcm3, hn1, hn2, hn3

app_name = 'questionnaire'


urlpatterns = [
    path("pddquizz1/", pddquizz1, name='pddquizz1'),
    path("pddquizz2/", pddquizz2, name='pddquizz2'),
    path("pddquizz3/", pddquizz3, name="pddquizz3"),
    path('pcm1/', pcm1, name="pcm1"),
    path('pcm2/', pcm2, name="pcm2"),
    path('pcm3/', pcm3, name="pcm3"),
    path('hn1/', hn1, name="hn1"),
    path('hn2/', hn2, name="hn2"),
    path('hn3/', hn3, name="hn3"),
    path('mdp&auth1/', mdp1, name="mdp1"),
    path('mdp&auth2/', mdp2, name="mdp2"),
    path("quizzrep/", quizzrep, name="quizzrep"),
]

GATE_website/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from questionnaire.models import Joueur


def index(request):
    context = {
        "connected":request.user.is_authenticated
    }
    return render(request, "GATE_website/index.html", context)


@login_required
def quizz(request):
    context = {
        'joueur': Joueur.objects.get(username=request.user.username)
    }
    return render(request, "GATE_website/quizz.html", context)

@login_required
def documentation(request):
    return render(request, "GATE_website/documentation.html")


def cgu(request):
    return render(request, "GATE_website/cg.html")

GATE_website/templates/GATE_website/cg.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Conditions générales d'utilisation | Log'INT</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/cg.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/717f408a62.js" crossorigin="anonymous"></script>
    <link rel="shortcut icon" type="image/png" href="{% static 'img/logoGATE.png' %}"/>
</head>
<body>

    {% include 'GATE_website/navbar.html' %}
    {% block content %}
    {% endblock %}
    <div class="main">
        <embed src="{% static 'pdf/CGU.pdf' %}" type="application/pdf" style="width: 100%; height:100vh">
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

</script>

</body>
</html>

GATE_website/templates/GATE_website/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Log'INT | Projet GATE 2023</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/717f408a62.js" crossorigin="anonymous"></script>
    <link rel="shortcut icon" type="image/png" href="{% static 'img/logoGATE.png' %}"/>
</head>
<body>

    {% if connected %}
        {% include 'GATE_website/quizznavbar.html' %}
    {% else %}
        {% include 'GATE_website/navbar.html' %}
    {% endif %}
        {% block content %}
        {% endblock %}

        <section id="background">
        <div class="title">
            <img class="child1" src="{% static "img/banner.jpg" %}" alt="home">
            <div class="above">
                <h1>LOG'INT</h1>
                <div class="parentIcon1">
                    <a href="https://www.instagram.com/log_int_2023/" target="_blank" rel="noopener noreferrer"><i class="fa-brands fa-instagram"></i></a>
                    <a href="https://www.linkedin.com/company/log-int2023/" target="_blank" rel="noopener noreferrer"><i class="fa-brands fa-linkedin"></i></a>
                    <a href="https://github.com/abonnivard/GATE_website" target="_blank" rel="noopener noreferrer"><i class="fa-brands fa-github"></i></a>

                </div>
            </div>
        </div>
            <div class="bloque" id="a-propos">
            <div class="texte">
                <h1>A propos de nous :</h1>
                <div class="line">
                </div>
                <p>Log’INT est un groupe de 7 étudiants de l’école Télécom SudParis ayant pour but de sensibiliser à la cybersécurité. Notre objectif est de pouvoir faire partie des chatons car leur vision s’aligne avec ce que nous souhaitons porter dans notre projet. Nous sommes actuellement en phase de candidature. </p>
            </div>
            <div class="image">
                <img src="{% static "img/about_right.jpg" %}" alt="test">
            </div>
        </div>
        <div class="bloque2">
            <div class="texte2">
                <h1>Ce qu'on fait :</h1>
                <div class="cadretexte">
                <p>Pour sensibiliser le plus de monde possible, nous allons proposer des conférences autour du thème de la cybersécurité à d’autres étudiants sur le campus de Télécom SudParis et nous comptons mettre en ligne un site fonctionnant sur le principe de l’initiative de l’Éducation Nationale PIX.
Notre site internet permettra d’accéder à différentes ressources pour améliorer son hygiène numérique, que ce soit de bons réflexes à prendre ou de sites plus respectueux de la vie privée des utilisateurs. Il y aura aussi une partie quiz, permettant de juger les connaissances acquises et redirigeant vers les ressources les plus à propos pour pallier au manque de connaissance.</p>
                </div>
            </div>
            <div class="image2">
                <img src="{% static 'img/software_img.jpg' %}" alt="image">
            </div>
        </div>
    </section>


        <footer>
        <div class="parentIcon">
            <a href="https://www.instagram.com/log_int_2023/" target="_blank" rel="noopener noreferrer"><i class="fa-brands fa-instagram"></i></a>
            <a href="https://www.linkedin.com/company/log-int2023/" target="_blank" rel="noopener noreferrer"><i class="fa-brands fa-linkedin"></i></a>
            <a href="https://github.com/abonnivard/GATE_website" target="_blank" rel="noopener noreferrer"><i class="fa-brands fa-github"></i></a>

        </div>
        <div class="copy">
            <p>Copyright © 2023 - Projet GATE Log'INT - <a href="../cgu/" target="_blank" rel="noopener noreferrer">Conditions générales d'utilisation</a>
            </p>

        </div>
    </footer>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

</body>
</html>

GATE_website/templates/GATE_website/navbar.html
{% load static %}
<header>
    <style>
        .dropdown-menu li:hover {
            background-color: rgba(123, 0, 44, 0.37);
            border-radius: 8%;
        }
    </style>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark" style="background-color:black ; padding: 0 ">
        <div class="container" style="padding-left: 0">
        <a href="../" class="navbar-brand mb-0 h1" style="padding: 0 ; justify-content: left">
            <img src="{% static "img/logo1.png" %}" style="height: 60px ;  margin-bottom: 5px " >
        </a>
        <button type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarNav"
                class="navbar-toggler"
                aria-controls="navbarNav"
                aria-expanded="false"
                aria-label="Toggle navigation">

            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="../" class="nav-link" style="transition: all .4s;">
                        Home
                    </a>
                </li>
                <li class="nav-item">
                    <a href="../quizz/" class="nav-link" style="transition: all .4s;">
                        Quizz
                    </a>
                </li>
                <li class="nav-item">
                    <a href="../documentation/" class="nav-link" style="transition: all .4s;">
                        Documentation
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'contact:contact' %}" class="nav-link" style="transition: all .4s;right: 10px;position: absolute;">
                        Nous contacter
                    </a>
                </li>
            </ul>
        </div>
        </div>
    </nav>
</header>

GATE_website/templates/GATE_website/quizz.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Quizz |Log'INT</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/quizz.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/717f408a62.js" crossorigin="anonymous"></script>
</head>
<body>
    {% include 'GATE_website/quizznavbar.html' %}
    {% block content %}
    {% endblock %}

    <section id="main">
        <div class="texte">
            <h1>Selectionner un Quizz</h1>
        </div>
    <div class="all">
        <div class="cadre1">
            <div class="texte1">
                <h1>Protection des données</h1>
            </div>
            <div class="all1">
            <div class="cadrein1">
                <div class="imagein1">
                    <img src="{% static 'img/kisspng-general-data-protection-regulation-information-pri-gdpr-5b0eab592b23a7.8898485115276880251767.png' %}" alt="">
                </div>
                <div class="niveau11">
                    <p>Niveau 1 : les bases</p>
                    <p style="font-size:0.8rem; margin-bottom: -20px; margin-top: -20px">Nécessite de se renseigner sur Cookie Scanner</p>
                </div>
                <div class="bas11">

                    <div class="bouton11">
                        <a href="{% url 'questionnaire:pddquizz1' %}" style="text-decoration: none; color: white">
                        <p>Jouer</p>
                        </a>
                    </div>

                    <div class="score11">
                        <p>Score : {{joueur.qcmpdd1pourcentage}} %</p>
                    </div>
                </div>
            </div>
            <div class="cadrein12">
                <div class="imagein12">
                    <img src="{% static 'img/kisspng-general-data-protection-regulation-information-pri-gdpr-5b0eab592b23a7.8898485115276880251767.png' %}" alt="">
                </div>
                <div class="niveau12">
                    <p>Niveau 2 : Intermediaire</p>
                    <p style="font-size:0.8rem; margin-bottom: -37px; margin-top: -20px">Nécessite de se renseigner sur exodus et Cookie Scanner</p>
                </div>
                <div class="bas12">
                    <div class="bouton12">
                        <a href="{% url 'questionnaire:pddquizz2' %}" style="text-decoration: none; color: white">
                            <p>Jouer</p>
                        </a>
                    </div>
                    <div class="score12">
                        <p>Score : {{joueur.qcmpdd2pourcentage}} %</p>
                    </div>
                </div>
            </div>
             <div class="cadrein13">
                <div class="imagein13">
                    <img src="{% static 'img/kisspng-general-data-protection-regulation-information-pri-gdpr-5b0eab592b23a7.8898485115276880251767.png' %}" alt="">
                </div>
                <div class="niveau13">
                    <p>Niveau 3 : Difficile</p>
                    <p style="font-size:0.8rem; margin-bottom: -20px; margin-top: -20px">Nécessite de se renseigner sur Cookie Scanner</p>
                </div>
                <div class="bas13">
                    <div class="bouton13">
                        <a href="{% url 'questionnaire:pddquizz3' %}" style="text-decoration: none; color: white">
                            <p>Jouer</p>
                        </a>
                    </div>
                    <div class="score13">
                        <p>Score : {{joueur.qcmpdd3pourcentage}} %</p>
                    </div>
                </div>
            </div>
        </div>

            <div class="progressbar1">
                    <div class="progressbar-level1" style="width: {{joueur.qcmpddTpourcentage}}%">
                        <p>{{joueur.qcmpddTpourcentage}}%</p>
                    </div>
            </div>
        </div>
<div class="cadre1">
            <div class="texte1">
                <h1>Protection contre les menaces</h1>
            </div>
            <div class="all1">
            <div class="cadrein2">
                <div class="imagein2">
                    <img src="{% static 'img/Cybersecurity.png' %}" alt="">
                </div>
                <div class="niveau21">
                    <p>Niveau 1 : les bases</p>
                </div>
                <div class="bas11">

                    <div class="bouton21">
                        <a href="{% url 'questionnaire:pcm1' %}" style="text-decoration: none; color: white">
                        <p>Jouer</p>
                        </a>
                    </div>

                    <div class="score21">
                        <p>Score : {{joueur.qcmpcm1pourcentage}} %</p>
                    </div>
                </div>
            </div>
            <div class="cadrein22">
                <div class="imagein22">
                    <img src="{% static 'img/Cybersecurity.png' %}" alt="">
                </div>
                <div class="niveau12">
                    <p>Niveau 2 : Intermediaire</p>
                    <p style="font-size:0.8rem; margin-bottom: -20px; margin-top: -20px">Nécessite de se renseigner sur VirusTotal</p>

                </div>
                <div class="bas12">
                    <div class="bouton22">
                        <a href="{% url 'questionnaire:pcm2' %}" style="text-decoration: none; color: white">
                        <p>Jouer</p>
                        </a>
                    </div>
                    <div class="score22">
                        <p>Score : {{joueur.qcmpcm2pourcentage}} %</p>
                    </div>
                </div>
            </div>
             <div class="cadrein23">
                <div class="imagein23">
                    <img src="{% static 'img/Cybersecurity.png' %}" alt="">
                </div>
                <div class="niveau23">
                    <p>Niveau 3 : Difficile</p>
                </div>
                <div class="bas13">
                    <div class="bouton23">
                        <a href="{% url 'questionnaire:pcm3' %}" style="text-decoration: none; color: white">
                        <p>Jouer</p>
                        </a>
                    </div>
                    <div class="score23">
                        <p>Score : {{joueur.qcmpcm3pourcentage}} %</p>
                    </div>
                </div>
            </div>
        </div>

            <div class="progressbar2">
                    <div class="progressbar-level2" style="width: {{joueur.qcmpcmTpourcentage}}%">
                        <p>{{joueur.qcmpcmTpourcentage}}%</p>
                    </div>
            </div>
        </div>
<div class="cadre1">
            <div class="texte1">
                <h1>Hygiène du numérique</h1>
            </div>
            <div class="all1">
            <div class="cadrein3">
                <div class="imagein3">
                    <img src="{% static 'img/cookies-comportement.png' %}" alt="">
                </div>
                <div class="niveau31">
                    <p>Niveau 1 : les bases</p>
                </div>
                <div class="bas11">

                    <div class="bouton31">
                        <a href="{% url 'questionnaire:hn1' %}" style="text-decoration: none; color: white">
                        <p>Jouer</p>
                        </a>
                    </div>

                    <div class="score31">
                        <p>Score : {{joueur.qcmhn1pourcentage}} %</p>
                    </div>
                </div>
            </div>
            <div class="cadrein32">
                <div class="imagein32">
                    <img src="{% static 'img/cookies-comportement.png' %}" alt="">
                </div>
                <div class="niveau32">
                    <p>Niveau 2 : Intermediaire</p>
                </div>
                <div class="bas32">
                    <div class="bouton32">
                        <a href="{% url 'questionnaire:hn2' %}" style="text-decoration: none; color: white">
                        <p>Jouer</p>
                        </a>
                    </div>
                    <div class="score32">
                        <p>Score : {{joueur.qcmhn2pourcentage}} %</p>
                    </div>
                </div>
            </div>
             <div class="cadrein33">
                <div class="imagein33">
                    <img src="{% static 'img/cookies-comportement.png' %}" alt="">
                </div>
                <div class="niveau33">
                    <p>Niveau 3 : Difficile</p>
                </div>
                <div class="bas33">
                    <div class="bouton33">
                        <a href="{% url 'questionnaire:hn3' %}" style="text-decoration: none; color: white">
                        <p>Jouer</p>
                        </a>
                    </div>
                    <div class="score33">
                        <p>Score : {{joueur.qcmhn3pourcentage}} %</p>
                    </div>
                </div>
            </div>
        </div>

            <div class="progressbar3">
                    <div class="progressbar-level3" style="width: {{joueur.qcmhnTpourcentage}}%">
                        <p>{{joueur.qcmhnTpourcentage}}%</p>
                    </div>
            </div>
        </div>
        <div class="cadre-mdp">
            <div class="texte1">
                <h1>Mot de passe et authentification</h1>
            </div>
            <div class="all1">
            <div class="cadrein4">
                <div class="imagein4">
                    <img src="{% static 'img/103089.png' %}" alt="">
                </div>
                <div class="niveau41">
                    <p>Niveau 1 : les bases</p>
                </div>
                <div class="bas11">

                    <div class="bouton41">
                        <a href="{% url 'questionnaire:mdp1' %}" style="text-decoration: none; color: white">
                        <p>Jouer</p>
                        </a>
                    </div>

                    <div class="score41">
                        <p>Score : {{joueur.qcmmea1pourcentage}} %</p>
                    </div>
                </div>
            </div>
            <div class="cadrein42">
                <div class="imagein42">
                    <img src="{% static 'img/103089.png' %}" alt="">
                </div>
                <div class="niveau42">
                    <p>Niveau 2 : Intermediaire</p>
                    <p style="font-size:0.8rem; margin-bottom: -20px; margin-top: -20px">Nécessite de se renseigner sur ProtonVPN</p>
                </div>
                <div class="bas42">
                    <div class="bouton42">
                        <a href="{% url 'questionnaire:mdp2' %}" style="text-decoration: none; color: white">
                            <p>Jouer</p>
                        </a>
                    </div>
                    <div class="score42">
                        <p>Score : {{joueur.qcmmea2pourcentage}} %</p>
                    </div>
                </div>
            </div>
        </div>

            <div class="progressbar4">
                    <div class="progressbar-level4" style="width: {{joueur.qcmmeaTpourcentage}}%">
                        <p>{{joueur.qcmmeaTpourcentage}}%</p>
                    </div>
            </div>
        </div>
    </div>
    </section>

     <footer>
        <div class="parentIcon">
            <a href="https://www.instagram.com/log_int_2023/" target="_blank" rel="noopener noreferrer"><i class="fa-brands fa-instagram"></i></a>
            <a href="https://www.linkedin.com/company/log-int2023/" target="_blank" rel="noopener noreferrer"><i class="fa-brands fa-linkedin"></i></a>
            <a href="https://github.com/abonnivard/GATE_website" target="_blank" rel="noopener noreferrer"><i class="fa-brands fa-github"></i></a>

        </div>
        <div class="copy">
            <p>Copyright © 2023 - Projet GATE Log'INT - <a href="../cgu/" target="_blank" rel="noopener noreferrer">Conditions générales d'utilisation</a>
            </p>
        </div>
    </footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

</body>
</html>

GATE_website/templates/GATE_website/quizznavbar.html
{% load static %}
<header>
    <style>
        .dropdown-menu li:hover {
            background-color: rgba(123, 0, 44, 0.37);
            border-radius: 8%;
        }

        @media screen and (min-width: 1000px) {
            #moncompte {
            right:50px;
            position: absolute;
        }

            #logout {
                right:5px;
                position: absolute;
            }
            #logout img{
                width: 30px;
            }
        }



    </style>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark" style="background-color:black ; padding: 0 ">
        <div class="container" style="padding-left: 0">
        <a href="../" class="navbar-brand mb-0 h1" style="padding: 0 ; justify-content: left">
            <img src="{% static "img/logo1.png" %}" style="height: 60px ; margin-bottom: 5px " >
        </a>
        <button type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarNav"
                class="navbar-toggler"
                aria-controls="navbarNav"
                aria-expanded="false"
                aria-label="Toggle navigation">

            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="../" class="nav-link" style="transition: all .4s;">
                        Home
                    </a>
                </li>
                <li class="nav-item">
                    <a href="../quizz/" class="nav-link" style="transition: all .4s;">
                        Quizz
                    </a>
                </li>

                <li class="nav-item">
                    <a href="../documentation/" class="nav-link" style="transition: all .4s;">
                        Documentation
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'contact:contact' %}" class="nav-link" style="transition: all .4s;">
                        Nous contacter
                    </a>
                </li>
                 <li class="nav-item">
                    <a href="{% url 'accounts:moncompte' %}" class="nav-link" style="transition: all .4s" id="moncompte">
                        Mon compte
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'accounts:logout' %}" class="nav-link" style="transition: all .4s;" id="logout">
                        <img src="{% static 'img/icon-logout.png' %}" alt="logout">
                    </a>
                </li>


            </ul>
        </div>
        </div>
    </nav>
</header>