GATE_website/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import index, quizz, documentation, cgu

app_name = 'GATE2'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('quizz/', quizz, name='quizz'),
    path('documentation/', documentation, name='documentation'),
    path('', include('accounts.urls')),
    path('',include('questionnaire.urls')),
    path('cgu/', cgu, name='cgu'),
]

accounts/urls.py
from django.contrib.auth import views
from django.urls import path

from GATE_website.views import index
from .forms import UserLoginForm
from .views import register, supprimer_compte, moncompte

app_name = 'accounts'


urlpatterns = [
    path('login/', views.LoginView.as_view(template_name="accounts/login.html", redirect_authenticated_user=True, authentication_form=UserLoginForm), name='login'),
    path('logout/', views.LogoutView.as_view(template_name="accounts/logout.html", next_page=index), name='logout'),
    path('register/', register, name='register'),
    path('moncompte/', moncompte, name='moncompte'),
    path('supprimer/', supprimer_compte, name='supprimer_compte'),

]

contact/urls.py
from django.contrib.auth import views
from django.urls import path
from .views import contact, redirection



app_name = 'contact'


urlpatterns = [
    path('nous-contacter/', contact, name='contact'),
    path('redirection/', redirection, name="redirection"),
]

accounts/models.py
# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User



class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control',
               'placeholder': 'Username',
               'id': 'username',
               }))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Password',
            'id': 'username',
        }
))

class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

accounts/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from GATE_website import views
from questionnaire.models import Joueur
from .forms import UserForm
from django.contrib.auth.decorators import login_required



# Create your views here.
def register(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            email = request.POST['email']
            password = request.POST['password1']
            username = request.POST['username']
            user = authenticate(request, email=email, password=password, username=username)
            if user is not None:
                login(request, user)
                new = Joueur(username=username)
                new.save()
            if request.user.is_authenticated:
                return redirect(views.quizz)
    else:
        form = UserForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/register.html', context)

@login_required
def moncompte(request):
    user = User.objects.all().filter(username=request.user.username)[0]
    context = {
        'user':user
    }
    return render(request, 'accounts/moncompte.html')


def supprimer_compte(request):
    joueur = Joueur.objects.all().filter(username=request.user.username)[0]
    user = User.objects.all().filter(username=request.user.username)[0]
    joueur.delete()
    user.delete()
    redirect(views.index)
    print('ok')
    return render(request, 'GATE_website/index.html')

accounts/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login | Porjet GATE 2023</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/717f408a62.js" crossorigin="anonymous"></script>
</head>
<body>

    {% include 'GATE_website/navbar.html' %}
    {% block content %}
    {% endblock %}


<div class="title">
    <div class="above">
        <img src="{% static 'img/banner.jpg' %}" alt="img">

        <div class="form">
            <h1>Se connecter</h1>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <a href="{% url 'accounts:register' %}">Pas encore de compte ?</a>
                <input id="submit" type="submit" value="Login" class="btn btn-secondary ml-1">
            </form>
        </div>
    </div>
</div>


    <footer>
        <div class="parentIcon">
            <a href="https://www.instagram.com/log_int_2023/" target="_blank" rel="noopener noreferrer"><i class="fa-brands fa-instagram"></i></a>
            <a href="https://www.linkedin.com/company/log-int2023/" target="_blank" rel="noopener noreferrer"><i class="fa-brands fa-linkedin"></i></a>
        </div>
        <div class="copy">
            <p>Copyright © 2023 - Projet GATE Log'INT - <a href="../cgu/" target="_blank" rel="noopener noreferrer">Conditions générales d'utilisation</a>
            </p>
        </div>
    </footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

accounts/templates/accounts/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

accounts/templates/accounts/moncompte.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Mon compte | Porjet GATE 2023</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/moncompte.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/717f408a62.js" crossorigin="anonymous"></script>
</head>
<body>

    {% include 'GATE_website/quizznavbar.html' %}
    {% block content %}
    {% endblock %}

    <div id="main">
        <div class="all">
            <div class="cadre">
                <h1>Votre compte</h1>
                <p>Pseudo : {{user.username}}</p>
                <p>Adresse email : {{user.email}}</p>
                <a href="{% url 'accounts:supprimer_compte' %}">Supprimer mon compte</a>
            </div>
        </div>
    </div>


    <footer>
        <div class="parentIcon">
            <a href="https://www.instagram.com/log_int_2023/" target="_blank" rel="noopener noreferrer"><i class="fa-brands fa-instagram"></i></a>
            <a href="https://www.linkedin.com/company/log-int2023/" target="_blank" rel="noopener noreferrer"><i class="fa-brands fa-linkedin"></i></a>
            <a href="https://github.com/abonnivard/GATE_website" target="_blank" rel="noopener noreferrer"><i class="fa-brands fa-github"></i></a>

        </div>
        <div class="copy">
            <p>Copyright © 2023 - Projet GATE Log'INT - <a href="../cgu/" target="_blank" rel="noopener noreferrer">Conditions générales d'utilisation</a>
            </p>
        </div>
    </footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

accounts/templates/accounts/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register | Porjet GATE 2023</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/register.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/717f408a62.js" crossorigin="anonymous"></script>
</head>
<body>

    {% include 'GATE_website/navbar.html' %}
    {% block content %}
    {% endblock %}


<div class="title">
    <div class="above">
        <img src="{% static 'img/banner.jpg' %}" alt="img">

        <div class="form">
            <h1>Se connecter</h1>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <input id="submit" type="submit" value="Sign up" class="btn btn-secondary ml-1">
            </form>
        </div>
    </div>
</div>


    <footer>
        <div class="parentIcon">
            <a href="https://www.instagram.com/log_int_2023/" target="_blank" rel="noopener noreferrer"><i class="fa-brands fa-instagram"></i></a>
            <a href="https://www.linkedin.com/company/log-int2023/" target="_blank" rel="noopener noreferrer"><i class="fa-brands fa-linkedin"></i></a>
            <a href="https://github.com/abonnivard/GATE_website" target="_blank" rel="noopener noreferrer"><i class="fa-brands fa-github"></i></a>

        </div>
        <div class="copy">
            <p>Copyright © 2023 - Projet GATE Log'INT - <a href="../cgu/" target="_blank" rel="noopener noreferrer">Conditions générales d'utilisation</a>
            </p>
        </div>
    </footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>